### ISSUE TITLE
Update EventDetailView to display set of attendees

### ISSUE THREAD

**Issue by Gilbb** [AY2425S1-CS2103T-T10-4/tp#100]
## Description
Update EventDetailView to display set of attendees

## Issue Type
Enhancement

## Acceptance Criteria
- [ ] Ensure that `EventDetailView` can dynamically update the attendees

**Comment by michaelyql** [comment]
This mainly has to do with #92 not updating the list of attendees for an event. 

`update` and `event` commands will update the attendee list.
