### ISSUE TITLE
Sort upcoming events for person by date ascending by default

### ISSUE THREAD

**Issue by michaelyql** [AY2425S1-CS2103T-T10-4/tp#113]
## Description
The 'Upcoming Events' section for person detail view shows the events but in an unsorted order. We should sort the events so it's more logical to the user to see which events are coming up soon.

## Issue Type
Enhancement

## Acceptance Criteria
- [x] Upcoming events for person detail view sorted ascending by date

## Screenshots/Visuals
<img width="525" alt="Screenshot 2024-10-24 at 1 04 47 AM" src="https://github.com/user-attachments/assets/cc7d0695-a6d5-41e8-9f01-a8f6df569daa">

**Comment by Gilbb** [comment]
Perhaps it would be better for the EventBook to be sorted by earliest date as well. If so, the event in the PersonDetailView would be sorted accordingly as well.
