### ISSUE TITLE
Adding event is not saved to storage, and does not reflect when app is closed and opened again

### ISSUE THREAD

**Issue by ashea10** [AY2425S1-CS2103T-T10-4/tp#129]
# Description

Adding an event is not saved to storage. Leaving the app and entering it again does not show the events added in previous session.

# Steps To Reproduce

1. Add an event (e.g. ``event -n Birthday Party -d 2023-10-15 -l Home -a 1 2 3``)
2. Exit the app
3. Enter the app, and the event above will not be reflected

# Expected Behavior

Event should be saved after being added, and should persist across sessions.

**Comment by marchjlim** [comment]
This bug doesn't exist in my local copy
