### ISSUE TITLE
Update feature success message contains invalid formatting of attendees

### ISSUE THREAD

**Issue by marchjlim** [AY2425S1-CS2103T-T10-4/tp#134]
## Description
Upon successfully updating an Event, the message displayed does not properly display Persons

## Steps to Reproduce
1. Enter a valid update command

## Expected Behavior
Each attendee should be enumerated without including unnecessary details such as seedu.address.model.person.Person

## Screenshots
![image](https://github.com/user-attachments/assets/33c299c6-a3bd-4f82-8124-6337706278fc)

**Comment by Gilbb** [comment]
Bug fixed
![image](https://github.com/user-attachments/assets/ce06a67a-a486-4b23-b5e4-718bf5d3dfe7)
