### ISSUE TITLE
list command not specifying command format

### ISSUE THREAD

**Issue by ashea10** [AY2425S1-CS2103T-T10-4/tp#137]
# Description

When the ``list`` command is input by the user (without parameters), the application outputs "unknown command" instead of outputting "invalid command format" like is the case for the other commands. The output should be something like:
``Invalid command format! 

list: Lists the address book or event book. Parameters: -p (for person book) or -e (for event book)
Example: list -p``

# Issue Type

Enhancement

**Comment by Gilbb** [comment]
I don't think this is necessary since `list -p` and `list -e` are the commands, which can be further emphasized in the user guide.
