### ISSUE TITLE
Clear -p command does not remove the attendee from the events

### ISSUE THREAD

**Issue by Gilbb** [AY2425S1-CS2103T-T10-4/tp#153]
## Description
Clear -p command does not remove the attendee from the events

## Steps to Reproduce
1. Clear -p

## Expected Behavior
The attendee list in events should be cleared.

![image](https://github.com/user-attachments/assets/0f0c8873-5012-42b9-aafb-da4268d321e0)

![image](https://github.com/user-attachments/assets/9818c325-b4bd-4170-be6b-efff5bd41926)

**Comment by michaelyql** [comment]
User may not want to clear the events, so we should just loop through all events and set the attendee list to a new attendee list
