### ISSUE TITLE
[PE-D][Tester A] Suggestion: Make the help window more useful

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-4/tp#183]
![image.png](https://raw.githubusercontent.com/Elinengu/ped/main/files/a91ed52e-a39a-48d5-a66d-5144f08c655b.png)
Currently the help windows shows the url to the user guide, however, it would be useful if the commands and command examples are being displayed in the help window.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Elinengu/ped#4

**Comment by michaelyql** [comment]
Technically we need to feature freeze, so we can't add more "things" to the app other than bug fixes

Can just include this under proposed features
