### ISSUE TITLE
[PE-D][Tester D] No way to delete events

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-4/tp#189]
![image.png](https://raw.githubusercontent.com/kaajinn/ped/main/files/edf33441-6743-463f-835f-356bf9339a67.png)

Should there be a way to delete events, just like persons? Otherwise, how can a user remove past events from the event book?

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: kaajinn/ped#3

**Comment by marchjlim** [comment]
There is a command, we just failed to include it in the UG. Will address this.
