### ISSUE TITLE
[PE-D][Tester B] Removing attendee from event functionality does not seem to work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-4/tp#192]
To replicate the bug:
1. Run the command update -i 3 -r 1

![image.png](https://raw.githubusercontent.com/JYL27/ped/main/files/eecc7646-e45d-49a0-ba41-371e90d88a66.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: JYL27/ped#3

**Comment by michaelyql** [comment]
This should be fixed by #240, it's a duplicated issue linked to event equality but different tester reported it
