### ISSUE TITLE
[PE-D][Tester B] Outdated Info Box and UML Diagram in Developer Guide under Model Component

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-4/tp#211]
![image.png](https://raw.githubusercontent.com/JYL27/ped/main/files/7a22e4f8-ee68-4756-8c4a-9d2a5cd82caf.png)

The info box and UML diagram mentions a Tag list that a Person references. However, the product does not seem to have a Tag list implemented.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: JYL27/ped#7

**Comment by marchjlim** [comment]
Duplicate bug
