### ISSUE TITLE
[PE-D][Tester A] Update event command does not work as intended

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-4/tp#216]
Let's use the first event in the sample data as example, this is how it looks originally:

![image.png](https://raw.githubusercontent.com/Elinengu/ped/main/files/1bd498f2-072d-4c62-9062-9ae4438c9bd7.png)

``update -i 1 -r 1`` does not remove Alex Yeoh from the  attendees list as stated in the UG.
![image.png](https://raw.githubusercontent.com/Elinengu/ped/main/files/cacffc53-aad8-4ff2-8466-9fcb6621ecfc.png)

Now I have added an event using:
`` event -n Test Party -sd 2023-10-15 -ed 2023-10-20 -l Test Location -a 1`` 

same for command:
``update -i 4 -a 2``  ``update -i 4 -a 2 -r 2``, both do not work and display the same error message

![image.png](https://raw.githubusercontent.com/Elinengu/ped/main/files/6bd68d11-b919-43b6-baed-c7d99a5ce476.png)

![image.png](https://raw.githubusercontent.com/Elinengu/ped/main/files/e418e240-6765-4719-b759-3d77cf09e72c.png)

However, command that swap out the attendees works correctly: ``update -i 4 -a 2 -r 1`` 
from:

![image.png](https://raw.githubusercontent.com/Elinengu/ped/main/files/279a7972-a739-4926-be4c-b4a26e97e844.png)

To:

![image.png](https://raw.githubusercontent.com/Elinengu/ped/main/files/922b8e53-c2cf-4891-9f87-3f5523d260e6.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Elinengu/ped#10

**Comment by michaelyql** [comment]
Should be fixed by event equality revert. See #240
