### ISSUE TITLE
[PE-D][Tester A] The error displayed incorrectly when the index provided but preamble is missing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-4/tp#228]
command used: 
`` update -i 4 Test Party``

![image.png](https://raw.githubusercontent.com/Elinengu/ped/main/files/94298704-a38a-4556-b4a6-87e843f0b926.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Elinengu/ped#13

**Comment by marchjlim** [comment]
I don't understand what is preamble.

**Comment by michaelyql** [comment]
Should be resolved by fixing #235
