### ISSUE TITLE
[PE-D][Tester A] The explaination for the UG is too brief

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-4/tp#233]
Personally I feel like the UI of this product is quite pretty and the idea that the contact panel can track the upcoming event and its location together with sorted start date is quite amazing. However, it is not being written in the UG.

Some users might take a while to realise it.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Elinengu/ped#16

**Comment by michaelyql** [comment]
Will add in Quick Start section
