### ISSUE TITLE
[PE-D][Tester A] Suggestion: make the email optional

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-4/tp#239]
Since the target user is going to save the contact for their relatives, it does not make sense for them to have every email for their relatives.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Elinengu/ped#21

**Comment by marchjlim** [comment]
I think that having an email makes sense for the value proposition, as the app is supposed to encapsulate an all-in-one event planner/tracker. It helps the user keep track of everything with ease.
