### ISSUE TITLE
Contact/Event list cards require double click to switch cards on Windows

### ISSUE THREAD

**Issue by michaelyql** [AY2425S1-CS2103T-T10-4/tp#90]
## Description
As per title

## Steps to Reproduce
1. Go to 'Events' or 'Contacts'.
2. Click on one card.
3. Click on another card.
4. Observe that two clicks are required to update the person or event detail view.

## Expected Behavior
Switching between cards should only require one click. 

## Screenshots
NA

## Additional Context
Application should be run in a Windows OS.

**Comment by Gilbb** [comment]
Event Card only requires on click on my WindowsOS

**Comment by michaelyql** [comment]
Should be closed by #98

Need more testing @ashea10
