### ISSUE TITLE
Deleting a person does not remove them from the attendee list

### ISSUE THREAD

**Issue by michaelyql** [AY2425S1-CS2103T-T10-4/tp#92]
## Description
We need to update the `delete` command to also remove `Person` objects from the attendee list of the events they are attending.

## Steps to Reproduce
1. Add a person to the attendee list of an event
2. Delete a person 
3. Observe that deleting a person does not remove them from the attendee list of the events they are attending

## Expected Behavior
- When a `Person` is deleted from the Contacts list, that person object should also be deleted from the event attendance list of all the events he or she is attending.
- UI for Contact list and Event attendee list should reflect the deletion of the person.

**Comment by Gilbb** [comment]
closed by #109
